/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppCommandRouteImport } from './routes/_app.command'
import { Route as AppCrmLeadIdRouteImport } from './routes/_app.crm.$leadId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadIdRoute = AppCrmLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/command': typeof AppCommandRoute
  '/crm': typeof AppCrmRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/hr': typeof AppHrRoute
  '/projects': typeof AppProjectsRoute
  '/crm/$leadId': typeof AppCrmLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/command': typeof AppCommandRoute
  '/crm': typeof AppCrmRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/hr': typeof AppHrRoute
  '/projects': typeof AppProjectsRoute
  '/crm/$leadId': typeof AppCrmLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/command': typeof AppCommandRoute
  '/_app/crm': typeof AppCrmRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/crm/$leadId': typeof AppCrmLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/command'
    | '/crm'
    | '/dashboard'
    | '/hr'
    | '/projects'
    | '/crm/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/command'
    | '/crm'
    | '/dashboard'
    | '/hr'
    | '/projects'
    | '/crm/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/command'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/hr'
    | '/_app/projects'
    | '/_app/crm/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command': {
      id: '/_app/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/$leadId': {
      id: '/_app/crm/$leadId'
      path: '/$leadId'
      fullPath: '/crm/$leadId'
      preLoaderRoute: typeof AppCrmLeadIdRouteImport
      parentRoute: typeof AppCrmRoute
    }
  }
}

interface AppCrmRouteChildren {
  AppCrmLeadIdRoute: typeof AppCrmLeadIdRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmLeadIdRoute: AppCrmLeadIdRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppRouteChildren {
  AppCommandRoute: typeof AppCommandRoute
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHrRoute: typeof AppHrRoute
  AppProjectsRoute: typeof AppProjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommandRoute: AppCommandRoute,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHrRoute: AppHrRoute,
  AppProjectsRoute: AppProjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
